---
title: "iteration_and_listcols"
output: github_document
date: "2022-10-30"
---

```{r setup}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  echo = TRUE, 
  warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
```


# Lists


```{r}
vec_numeric = 5:8
vec_logical = c(TRUE, TRUE, TRUE, FALSE)
```

 Lets look at a lsit
 
```{r}
l = list(
  vec_numeric = 5:8,
  mat         = matrix(1:8, 2, 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(1000))
)
```
 

Accessing list items 

```{r}
l$vec_numeric

l[[3]]

l[["mat"]]
```


Let's write a for loop

```{r}
list_norms = 
  list(
    a = rnorm(20, 5, 4),
    b = rnorm(20, -12, 3),
    c = rnorm(20, 17, .4),
    d = rnorm(20, 100, 1)
  )

is.list(list_norms)
```


```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```


```{r}
mean_and_sd(list_norms[[1]])
mean_and_sd(list_norms[[2]])
mean_and_sd(list_norms[[3]])
mean_and_sd(list_norms[[4]])
```


Let's a `for` loop 

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}

output
```


# Can we do map?
 
```{r}
output = map(list_norms, mean_and_sd)
```


```{r}
map(list_norms, median)
```


```{r}
map_dbl(list_norms, median)

map_df(list_norms, mean_and_sd)
```


# list columns

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    norm = list_norms
  )

listcol_df[["norm"]]

output = map(listcol_df[["norm"]], mean_and_sd)
map_df(listcol_df[["norm"]], mean_and_sd)
```

can we add list column and then wah t

```{r}
listcol_df = 
  listcol_df %>% 
  mutate(
    m_sd = map_df(norm, mean_and_sd)) %>% 
  select(-norm)

listcol_df
```


# what about something mroe realistic

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

let's nest within weather stations
```{r}
weather_nest_df = 
  weather_df %>% 
    nest(data = date:tmin)

```

```{r}
weather_nest_df [["data"]]
```


linear regression
```{r}
weather_nest_df[["data"]][[1]]

lm(tmax ~tmin, data = weather_nest_df[["data"]][[1]])
lm(tmax ~tmin, data = weather_nest_df[["data"]][[2]])
lm(tmax ~tmin, data = weather_nest_df[["data"]][[3]])
```

Let's write a shor lil ol function

```{r}

weather_lm = function(df) {
  lm(tmax ~tmin, data = df)
}

weather_lm(weather_nest_df[["data"]][[1]])

map(weather_nest_df[["data"]], weather_lm)
```


```{r}
weather_nest_df %>% 
  mutate(
    model = map(data, weather_lm)
  )
```

unnesting
```{r}
weather_nest_df %>% 
  unnest(data)
```



```{r}
read_page_reviews = function(url){
  
  dynamite_html = read_html(url)

  review_titles = 
    dynamite_html %>%
    html_nodes(".a-text-bold span") %>%
    html_text()

  review_stars = 
    dynamite_html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("^\\d") %>%
    as.numeric()

  review_text = 
    dynamite_html %>%
    html_nodes(".review-text-content span") %>%
    html_text() %>% 
    str_replace_all("\n", "") %>% 
    str_trim()%>% 
    str_subset("The media could not be loaded.", negate = TRUE) %>% 
    str_subset("^$", negate = TRUE)

  reviews = tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
)
  
  reviews
}
```


What we did last time
```{r}
base_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

vec_url = str_c(base_url, c(1, 2, 3, 4, 5))

dynamite_reviews = 
  bind_rows(
    read_page_reviews(vec_url[1]),
    read_page_reviews(vec_url[2]),
    read_page_reviews(vec_url[3]),
    read_page_reviews(vec_url[4]),
    read_page_reviews(vec_url[5])
  )

dynamite_reviews

```


```{r}
map(vec_url, read_page_reviews )
```

```{r}
n_reviews = 
  tibble(
    page = 1:5,
    page_url = str_c(base_url, page)) %>% 
  mutate(
    reviews = map(page_url, read_page_reviews))
  

n_reviews %>% 
  select(-page_url) %>% 
  unnest(reviews)

```

